# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gotin(object):
    def setupUi(self, Gotin):
        Gotin.setObjectName("Gotin")
        Gotin.resize(800, 245)
        Gotin.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Gotin.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Gotin)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 771, 121))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 16px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.newsPath = QtWidgets.QLabel(self.groupBox)
        self.newsPath.setGeometry(QtCore.QRect(10, 10, 691, 41))
        self.newsPath.setStyleSheet("border: 2px solid #ccc;\n"
"font: 18px \"微软雅黑\";\n"
"border-radius: 20px;\n"
"background: #fff;\n"
"padding-left: 10px;\n"
"padding-right: 15px;\n"
"color: SlateGray;")
        self.newsPath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.newsPath.setObjectName("newsPath")
        self.tempPath = QtWidgets.QLabel(self.groupBox)
        self.tempPath.setGeometry(QtCore.QRect(10, 70, 691, 41))
        self.tempPath.setStyleSheet("border: 2px solid #ccc;\n"
"font: 18px \"微软雅黑\";\n"
"border-radius: 20px;\n"
"background: #fff;\n"
"padding-left: 10px;\n"
"padding-right: 15px;\n"
"color: SlateGray;")
        self.tempPath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tempPath.setObjectName("tempPath")
        self.newsBtn = QtWidgets.QPushButton(self.groupBox)
        self.newsBtn.setGeometry(QtCore.QRect(710, 13, 51, 34))
        self.newsBtn.setStyleSheet("font: 18px \"微软雅黑\";")
        self.newsBtn.setObjectName("newsBtn")
        self.tempBtn = QtWidgets.QPushButton(self.groupBox)
        self.tempBtn.setGeometry(QtCore.QRect(710, 73, 51, 34))
        self.tempBtn.setStyleSheet("font: 18px \"微软雅黑\";")
        self.tempBtn.setObjectName("tempBtn")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(70, 205, 711, 31))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border: 4px solid transparent;\n"
"    border-radius: 14px;\n"
"    background: SlateGray;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 188, 801, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 61, 21))
        self.label_3.setStyleSheet("font: 18px \"微软雅黑\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.dateStart = QtWidgets.QDateEdit(self.centralwidget)
        self.dateStart.setGeometry(QtCore.QRect(30, 146, 150, 36))
        self.dateStart.setStyleSheet("font: 18px \"微软雅黑\";")
        self.dateStart.setAlignment(QtCore.Qt.AlignCenter)
        self.dateStart.setCalendarPopup(True)
        self.dateStart.setObjectName("dateStart")
        self.dateEnd = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEnd.setGeometry(QtCore.QRect(230, 146, 150, 36))
        self.dateEnd.setStyleSheet("font: 18px \"微软雅黑\";")
        self.dateEnd.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEnd.setCalendarPopup(True)
        self.dateEnd.setObjectName("dateEnd")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 149, 51, 31))
        self.label_4.setStyleSheet("font: 18px \"微软雅黑\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(386, 130, 16, 66))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1, 120, 20, 75))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(771, 120, 20, 75))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(410, 145, 356, 37))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calcBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.calcBtn.setStyleSheet("font: 18px \"微软雅黑\";")
        self.calcBtn.setObjectName("calcBtn")
        self.horizontalLayout.addWidget(self.calcBtn)
        self.resetBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.resetBtn.setStyleSheet("font: 18px \"微软雅黑\";")
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout.addWidget(self.resetBtn)
        self.exitBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.exitBtn.setStyleSheet("font: 18px \"微软雅黑\";")
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout.addWidget(self.exitBtn)
        Gotin.setCentralWidget(self.centralwidget)

        self.retranslateUi(Gotin)
        QtCore.QMetaObject.connectSlotsByName(Gotin)

    def retranslateUi(self, Gotin):
        _translate = QtCore.QCoreApplication.translate
        Gotin.setWindowTitle(_translate("Gotin", "Gotin"))
        self.newsPath.setText(_translate("Gotin", "尚未打开消息文本文件"))
        self.tempPath.setText(_translate("Gotin", "尚未打开 Excel 表文件"))
        self.newsBtn.setText(_translate("Gotin", "..."))
        self.tempBtn.setText(_translate("Gotin", "..."))
        self.progressBar.setFormat(_translate("Gotin", "%p%"))
        self.label_3.setText(_translate("Gotin", "进度"))
        self.dateStart.setDisplayFormat(_translate("Gotin", "yyyy-MM-dd"))
        self.dateEnd.setDisplayFormat(_translate("Gotin", "yyyy-MM-dd"))
        self.label_4.setText(_translate("Gotin", "至"))
        self.calcBtn.setText(_translate("Gotin", "计算导出"))
        self.resetBtn.setText(_translate("Gotin", "重置应用"))
        self.exitBtn.setText(_translate("Gotin", "退出程序"))
import main_rc
